*Topic*: Data Science  
*Author*: Luz Enseñat de Carlos

# Student Grade Data Processing

We will use Pandas to manage and transform the data.

In [ ]:
import pandas as pd

In this project, we will work with a dataset containing information about students and their grades. The file *students-mat.csv* was obtained from the UCI Machine Learning Repository. To access the full dataset description, visit the following link: [Student Performance Data Set](https://archive.ics.uci.edu/ml/datasets/Student+Performance).

### 1. Data Loading

We read the CSV file called *students-mat.csv* and store it in a Pandas DataFrame named `students`.

In [ ]:
# We read the students file and store it in a DataFrame, specifying that the field separator is ';':

students = pd.read_csv("https://raw.githubusercontent.com/Luz-Ensenat/Students_Data_Processing/main/data/student-mat.csv", sep=';')

students

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [ ]:
# We inspect the number of rows and columns and print the result:

print("Rows and columns in the students DataFrame:", students.shape)

Rows and columns in the students DataFrame: (395, 33)

### 2. Filtering Underage Students

In this analysis, we will only consider students younger than 18 years old. Therefore, we overwrite the `students` DataFrame so that it only contains underage students.

In [ ]:
# We apply the filter to keep only underage students:

students = students[students['age'] < 18]

students

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,MS,F,17,U,GT3,T,2,2,other,at_home,...,3,4,3,1,1,3,8,13,11,11
373,MS,F,17,R,GT3,T,1,2,other,other,...,3,5,5,1,3,1,14,6,5,5
379,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,17,10,10,10
382,MS,M,17,U,GT3,T,2,3,other,services,...,4,4,3,1,1,3,2,11,11,10
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16

### 3. Renaming Columns

The columns G1, G2, and G3 contain the students' grades for three evaluation periods. We rename these columns to `grade1`, `grade2`, and `grade3`, respectively.

In [ ]:
# We rename the columns G1, G2, and G3 using the rename method:

students = students.rename(columns={'G1':'grade1','G2':'grade2','G3':'grade3'})

students

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,grade1,grade2,grade3
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,MS,F,17,U,GT3,T,2,2,other,at_home,...,3,4,3,1,1,3,8,13,11,11
373,MS,F,17,R,GT3,T,1,2,other,other,...,3,5,5,1,3,1,14,6,5,5
379,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,17,10,10,10
382,MS,M,17,U,GT3,T,2,3,other,services,...,4,4,3,1,1,3,2,11,11,10
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16

### 4. Column Filtering

We reduce the size of the DataFrame to keep only the columns relevant to our analysis. We retain the following columns: `school`, `sex`, `age`, `activities`, and the renamed columns `grade1`, `grade2`, and `grade3`.

We overwrite the `students` DataFrame with the filtered result.

In [ ]:
# We create a new DataFrame containing only the columns relevant to the analysis and overwrite the students DataFrame:

cols_keep = ['school','sex','age','activities','grade1','grade2','grade3']
students = students[cols_keep]

students

    school sex  age activities  grade1  grade2  grade3
1       GP   F   17         no       5       5       6
2       GP   F   15         no       7       8      10
3       GP   F   15        yes      15      14      15
4       GP   F   16         no       6      10      10
5       GP   M   16        yes      15      15      15
..     ...  ..  ...        ...     ...     ...     ...
372     MS   F   17        yes      13      11      11
373     MS   F   17        yes       6       5       5
379     MS   F   17        yes      10      10      10
382     MS   M   17        yes      11      11      10
391     MS   M   17         no      14      16      16

[284 rows x 7 columns]

### 5. Calculation of Students Passing Each Evaluation Period

First, we create three boolean columns (`grade1_passed`, `grade2_passed`, `grade3_passed`) indicating whether the student passed each evaluation period.

A student passes if the grade is greater than or equal to 10.

In [ ]:
# We identify students who passed each grade by creating the three corresponding columns.
# We use loc to avoid the SettingWithCopyWarning error:

for i in (1, 2, 3):
    students.loc[:, f'grade{i}_passed'] = students[f'grade{i}'] >= 10

students

/tmp/ipykernel_9861/3371536756.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students.loc[:, f'grade{i}_passed'] = students[f'grade{i}'] >= 10
/tmp/ipykernel_9861/3371536756.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students.loc[:, f'grade{i}_passed'] = students[f'grade{i}'] >= 10
/tmp/ipykernel_9861/3371536756.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students.loc[:, f'grade{i}_passed'] = students[f'grade{i}'] >= 10

,school,sex,age,activities,grade1,grade2,grade3,grade1_passed,grade2_passed,grade3_passed
1,GP,F,17,no,5,5,6,False,False,False
2,GP,F,15,no,7,8,10,False,False,True
3,GP,F,15,yes,15,14,15,True,True,True
4,GP,F,16,no,6,10,10,False,True,True
5,GP,M,16,yes,15,15,15,True,True,True
...,...,...,...,...,...,...,...,...,...,...
372,MS,F,17,yes,13,11,11,True,True,True
373,MS,F,17,yes,6,5,5,False,False,False
379,MS,F,17,yes,10,10,10,True,True,True
382,MS,M,17,yes,11,11,10,True,True,True
391,MS,M,17,no,14,16,16,True,True,True

We can now count the number of students who passed each evaluation period.

We will determine how many students passed all three evaluation periods and how many failed all of them.

In [ ]:
# We calculate how many students passed all three evaluation periods and how many failed all of them:

passed_all = students[students[['grade1_passed','grade2_passed','grade3_passed']].all(axis=1)].shape[0]
failed_all = students[~students[['grade1_passed','grade2_passed','grade3_passed']].any(axis=1)].shape[0]

# We print the results:

print("Students who passed all three evaluation periods:", passed_all)
print("Students who failed all evaluation periods:", failed_all)

Students who passed all three evaluation periods: 167
Students who failed all evaluation periods: 61

### 6. Average Grade per Student

We calculate the average grade for each student and add a new column to the DataFrame called `final_grade`.

In [ ]:
# We calculate the average grade for each student using mean and axis=1 so that the average is computed row by row.
# Once again, we use loc to avoid the SettingWithCopyWarning error:

students.loc[:, 'final_grade'] = students[['grade1', 'grade2', 'grade3']].mean(axis=1)

students

/tmp/ipykernel_9861/2337967201.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students.loc[:, 'final_grade'] = students[['grade1', 'grade2', 'grade3']].mean(axis=1)

,school,sex,age,activities,grade1,grade2,grade3,grade1_passed,grade2_passed,grade3_passed,final_grade
1,GP,F,17,no,5,5,6,False,False,False,5.333333
2,GP,F,15,no,7,8,10,False,False,True,8.333333
3,GP,F,15,yes,15,14,15,True,True,True,14.666667
4,GP,F,16,no,6,10,10,False,True,True,8.666667
5,GP,M,16,yes,15,15,15,True,True,True,15.000000
...,...,...,...,...,...,...,...,...,...,...,...
372,MS,F,17,yes,13,11,11,True,True,True,11.666667
373,MS,F,17,yes,6,5,5,False,False,False,5.333333
379,MS,F,17,yes,10,10,10,True,True,True,10.000000
382,MS,M,17,yes,11,11,10,True,True,True,10.666667
391,MS,M,17,no,14,16,16,True,True,True,15.333333

### 7. Average Final Grade by Age and Gender

We calculate the average final grade of students grouped by age and gender, rounding the result to two decimal places.

The result is stored in a DataFrame called `final_grade_stats`, and the output is sorted from highest to lowest average grade.

In [ ]:
# We group the data by age and gender, round the average grade values, and sort the results in descending order:

final_grade_stats = (
    students.groupby(['age','sex'], as_index=False)['final_grade']
    .mean()
    .round(2)
    .sort_values('final_grade', ascending=False)
)

print(final_grade_stats)

   age sex  final_grade
1   15   M        12.57
3   16   M        11.66
4   17   F        10.82
2   16   F        10.49
5   17   M        10.16
0   15   F         9.80

### 8. Duplicate Values

The `students` DataFrame may contain duplicate rows, so we identify and remove them.

In [ ]:
# We calculate the number of duplicate rows, print the result, and remove duplicates using drop_duplicates if necessary:

n_dup = students.duplicated().sum()

print("Duplicate rows:", n_dup)

if n_dup > 0:
    students = students.drop_duplicates()
    print("Duplicates removed.")

Duplicate rows: 15
Duplicates removed.