*Tema*: Data Science\
*Autora*: Luz Enseñat de Carlos

# Tratamiento de Datos de Notas de Estudiantes

Utilizaremos Pandas para manejar y transformar los datos

In [19]:
import pandas as pd

En este proyecto vamos a trabajar con un conjunto de datos que contiene información sobre estudiantes y sus notas. El fichero *students-mat.csv* ha sido extraído del repositorio de Machine Learning de la UCI. Para consultar la descripción completa del conjunto de datos, se puede visitar el siguiente enlace: [Student Performance Data Set](https://archive.ics.uci.edu/ml/datasets/Student+Performance).

### 1. Carga de Datos

Leemos el fichero CSV llamado *students-mat.csv* y lo almacenamos en un DataFrame de Pandas llamado `students`.

In [20]:
# Leemos el ficheros de students almacenándolo en un DataFrame, especificando que el separador de campos es ';':

students = pd.read_csv("https://raw.githubusercontent.com/Luz-Ensenat/Students_Data_Processing/main/data/student-mat.csv", sep=';')

students

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [21]:
# Vemos el nº de filas y columnas y lo imprimimos:

print("Filas y columnas del DataFrame students:", students.shape)

Filas y columnas del DataFrame students: (395, 33)

### 2. Filtro estudiantes mayores de edad

En nuestro estudio vamos a considerar solo a los estudiantes menores de 18 años, por lo que sobrescribiremos el DataFrame `students` para que contendrá solo a los estudiantes menores de edad.

In [22]:
# Aplicamos el fitro para dejar sólo estudiantes menores de edad:

students = students[students['age'] < 18]

students

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,MS,F,17,U,GT3,T,2,2,other,at_home,...,3,4,3,1,1,3,8,13,11,11
373,MS,F,17,R,GT3,T,1,2,other,other,...,3,5,5,1,3,1,14,6,5,5
379,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,17,10,10,10
382,MS,M,17,U,GT3,T,2,3,other,services,...,4,4,3,1,1,3,2,11,11,10
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16

### 3. Renombrar columnas

Las columnas G1, G2 y G3 contienen las notas de los estudiantes en tres cursos. Renombraremos estas columnas a `grade1`, `grade2` y `grade3` respectivamente.

In [23]:
# Renombramos las columnas G1, G2 y G3 mediante el método rename:

students = students.rename(columns={'G1':'grade1','G2':'grade2','G3':'grade3'})

students

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,grade1,grade2,grade3
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,MS,F,17,U,GT3,T,2,2,other,at_home,...,3,4,3,1,1,3,8,13,11,11
373,MS,F,17,R,GT3,T,1,2,other,other,...,3,5,5,1,3,1,14,6,5,5
379,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,17,10,10,10
382,MS,M,17,U,GT3,T,2,3,other,services,...,4,4,3,1,1,3,2,11,11,10
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16

### 4. Filtrado de columnas

Vamos a reducir el tamaño del dataframe a solo las columnas que nos interesan. Mantendremos las siguientes columnas: `school`, `sex`, `age`, `activities` y las renombradas `grade1`, `grade2`, `grade3`. Sobrescribiremos el DataFrame `students` con el resultado.

In [24]:
# Creamos un nuevo DataFrame sólo con las columnas que nos interesan y sobreescribimos students con él:

cols_keep = ['school','sex','age','activities','grade1','grade2','grade3']
students = students[cols_keep]

students

    school sex  age activities  grade1  grade2  grade3
1       GP   F   17         no       5       5       6
2       GP   F   15         no       7       8      10
3       GP   F   15        yes      15      14      15
4       GP   F   16         no       6      10      10
5       GP   M   16        yes      15      15      15
..     ...  ..  ...        ...     ...     ...     ...
372     MS   F   17        yes      13      11      11
373     MS   F   17        yes       6       5       5
379     MS   F   17        yes      10      10      10
382     MS   M   17        yes      11      11      10
391     MS   M   17         no      14      16      16

[284 rows x 7 columns]

### 5. Calculo de aprobados por curso

Primero crearemos tres columnas de tipo booleano (`grade1_passed`, `grade2_passed`, `grade3_passed`) que indiquen si el estudiante ha aprobado cada uno de los cursos. Un estudiante aprueba si su nota es mayor o igual a 10.

In [25]:
# Vemos los alumnos que han aprobado cada grade, creando las 3 columnas correspondientes y usamos loc para evitar el error SettingWithCopyWarning:

for i in (1, 2, 3):
    students.loc[:, f'grade{i}_passed'] = students[f'grade{i}'] >= 10

students

/tmp/ipykernel_1015/1890113353.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students.loc[:, f'grade{i}_passed'] = students[f'grade{i}'] >= 10
/tmp/ipykernel_1015/1890113353.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students.loc[:, f'grade{i}_passed'] = students[f'grade{i}'] >= 10
/tmp/ipykernel_1015/1890113353.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students.loc[:, f'grade{i}_passed'] = students[f'grade{i}'] >= 10

,school,sex,age,activities,grade1,grade2,grade3,grade1_passed,grade2_passed,grade3_passed
1,GP,F,17,no,5,5,6,False,False,False
2,GP,F,15,no,7,8,10,False,False,True
3,GP,F,15,yes,15,14,15,True,True,True
4,GP,F,16,no,6,10,10,False,True,True
5,GP,M,16,yes,15,15,15,True,True,True
...,...,...,...,...,...,...,...,...,...,...
372,MS,F,17,yes,13,11,11,True,True,True
373,MS,F,17,yes,6,5,5,False,False,False
379,MS,F,17,yes,10,10,10,True,True,True
382,MS,M,17,yes,11,11,10,True,True,True
391,MS,M,17,no,14,16,16,True,True,True

Ahora podemos contar el número de estudiantes que han aprobado cada curso. Veremos cuántos estudiantes han aprobado los tres cursos y cuántos no han aprobado ninguno

In [26]:
# Medimos los que han aprobado los 3 cursos y los que no han aprobado ninguno:

passed_all   = students[students[['grade1_passed','grade2_passed','grade3_passed']].all(axis=1)].shape[0]
failed_all   = students[~students[['grade1_passed','grade2_passed','grade3_passed']].any(axis=1)].shape[0]

# Imprimimos los resultados:

print("Aprobados los 3 cursos:", passed_all)
print("No aprobó ninguno:",    failed_all)

Aprobados los 3 cursos: 167
No aprobó ninguno: 61

### 6. Nota media por estudiante

Calcularemos la nota media de cada estudiante y añadiremos una nueva columna al DataFrame llamada `final_grade`.

In [27]:
# Calculamos la nota media de cada alumno mediante mean y usando axis=1 para que calcule la media por fila. De nuevo usamos loc para evitar el error SettingWithCopyWarning:

students.loc[:, 'final_grade'] = students[['grade1', 'grade2', 'grade3']].mean(axis=1)

students

/tmp/ipykernel_1015/383220301.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students.loc[:, 'final_grade'] = students[['grade1', 'grade2', 'grade3']].mean(axis=1)

,school,sex,age,activities,grade1,grade2,grade3,grade1_passed,grade2_passed,grade3_passed,final_grade
1,GP,F,17,no,5,5,6,False,False,False,5.333333
2,GP,F,15,no,7,8,10,False,False,True,8.333333
3,GP,F,15,yes,15,14,15,True,True,True,14.666667
4,GP,F,16,no,6,10,10,False,True,True,8.666667
5,GP,M,16,yes,15,15,15,True,True,True,15.000000
...,...,...,...,...,...,...,...,...,...,...,...
372,MS,F,17,yes,13,11,11,True,True,True,11.666667
373,MS,F,17,yes,6,5,5,False,False,False,5.333333
379,MS,F,17,yes,10,10,10,True,True,True,10.000000
382,MS,M,17,yes,11,11,10,True,True,True,10.666667
391,MS,M,17,no,14,16,16,True,True,True,15.333333

### 7. Nota media final por edad y sexo

Calcularemos la nota media final de los estudiantes por edad y sexo y redondearemos el resultado a dos decimales. Almacenaremos el resultado en un DataFrame llamado `final_grade_stats` y ordenamos el resultado por nota media de mayor a menor.

In [28]:
# Agrupamos por edad y sexo, redondeamos la nota media y organizamos los resultados en order descendente:

final_grade_stats = (students.groupby(['age','sex'], as_index=False)['final_grade'].mean().round(2).sort_values('final_grade', ascending=False))
print(final_grade_stats)

   age sex  final_grade
1   15   M        12.57
3   16   M        11.66
4   17   F        10.82
2   16   F        10.49
5   17   M        10.16
0   15   F         9.80

### 8. Valores duplicados

Hay alguna fila duplicada en el DataFrame `students`, por lo que las eliminaremos.

In [29]:
# Calculamos la cantidad de duplicados que hay, la imprimimos y, si es mayor que 0, eliminamos estos duplicados mediante drop:

n_dup = students.duplicated().sum()
print("Filas duplicadas:", n_dup)
if n_dup > 0:
    students = students.drop_duplicates()
    print("Duplicados eliminados.")

Filas duplicadas: 15
Duplicados eliminados.